# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "03c65e832a482f2f5bc75e9f5a4d3056"
application_url = "https://mainland-jerry-title-sources.trycloudflare.com"
embedded = true
name = "reviews"
handle = "reviews-126"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bryt-takehome.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://mainland-jerry-title-sources.trycloudflare.com/auth/callback",
  "https://mainland-jerry-title-sources.trycloudflare.com/auth/shopify/callback",
  "https://mainland-jerry-title-sources.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://mainland-jerry-title-sources.trycloudflare.com/api/public"
subpath = "reviewer-9000"
prefix = "apps"

[pos]
embedded = false
